# 验证码识别系统配置文件

# 应用配置
app:
  name: "captcha-recognizer"
  version: "1.0.0"
  debug: false
  log_level: "INFO"

# 识别配置
recognition:
  default_type: "text"
  max_image_size: 16777216  # 16MB
  supported_formats:
    - "png"
    - "jpg"
    - "jpeg"
    - "gif"
    - "bmp"
  timeout: 30.0
  retry_count: 3

# 缓存配置
cache:
  enabled: true
  type: "memory"  # memory, redis
  max_size: 1000
  ttl: 3600  # 1小时
  redis_url: "redis://localhost:6379/0"

# 日志配置
logging:
  level: "INFO"
  format: "json"  # json, text
  file: "logs/captcha_recognizer.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5
  console_output: true

# 性能配置
performance:
  monitor_enabled: true
  slow_threshold: 2.0
  max_history: 1000

# API配置
api:
  host: "0.0.0.0"
  port: 5000
  debug: false
  rate_limit:
    enabled: true
    default_limit: "1000 per hour"
    per_method_limits:
      "POST /api/recognize/upload": "100 per minute"
      "POST /api/recognize/url": "50 per minute"
      "POST /api/recognize/base64": "100 per minute"

# 安全配置
security:
  api_key_required: false
  jwt_secret: "your-secret-key-change-in-production"
  jwt_expiration: 3600  # 1小时
  cors_enabled: true
  cors_origins:
    - "*"
